package life.mygig.clauderc.ui.screens

import androidx.activity.compose.rememberLauncherForActivityResult
import androidx.activity.result.contract.ActivityResultContracts
import androidx.compose.foundation.layout.heightIn
import life.mygig.clauderc.notify.SessionWatcher
import androidx.compose.foundation.background
import androidx.compose.foundation.border
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.size
import androidx.compose.foundation.shape.CircleShape
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.sp
import life.mygig.clauderc.ui.components.CardBox
import life.mygig.clauderc.ui.components.Health
import life.mygig.clauderc.ui.components.PillTabs
import life.mygig.clauderc.ui.components.SectionLabel
import life.mygig.clauderc.ui.components.StatusDot
import life.mygig.clauderc.ui.theme.Term

import android.content.ClipData
import android.content.ClipboardManager
import android.content.Context
import android.content.Intent
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.text.KeyboardOptions
import androidx.compose.foundation.text.selection.SelectionContainer
import androidx.compose.foundation.verticalScroll
import androidx.compose.material.icons.Icons
import life.mygig.clauderc.ui.components.Visibility
import life.mygig.clauderc.ui.components.VisibilityOff
import androidx.compose.material3.AlertDialog
import androidx.compose.material3.Button
import androidx.compose.material3.Card
import androidx.compose.material3.HorizontalDivider
import androidx.compose.material3.Icon
import androidx.compose.material3.IconButton
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.OutlinedButton
import androidx.compose.material3.OutlinedTextField
import androidx.compose.material3.SegmentedButton
import androidx.compose.material3.SegmentedButtonDefaults
import androidx.compose.material3.SingleChoiceSegmentedButtonRow
import androidx.compose.material3.Switch
import androidx.compose.material3.Text
import androidx.compose.material3.TextButton
import androidx.compose.runtime.Composable
import androidx.compose.runtime.collectAsState
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableIntStateOf
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.rememberCoroutineScope
import androidx.compose.runtime.saveable.rememberSaveable
import androidx.compose.runtime.setValue
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.focus.onFocusChanged
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.text.font.FontFamily
import androidx.compose.ui.text.input.KeyboardType
import androidx.compose.ui.text.input.PasswordVisualTransformation
import androidx.compose.ui.text.input.VisualTransformation
import androidx.compose.ui.unit.dp
import life.mygig.clauderc.BuildConfig
import life.mygig.clauderc.api.Updates
import life.mygig.clauderc.data.AppSettings
import life.mygig.clauderc.data.Server
import life.mygig.clauderc.data.ThemeMode
import life.mygig.clauderc.ssh.HostKeyInfo
import kotlinx.coroutines.launch
import life.mygig.clauderc.ui.LocalAppLock
import life.mygig.clauderc.ui.MainViewModel

@Composable
fun SettingsScreen(vm: MainViewModel, s: AppSettings, firstRun: Boolean) {
    val context = LocalContext.current
    val publicKey by vm.publicKey.collectAsState()
    val busy by vm.busy.collectAsState()

    // Blank by default: nothing about any server ships with the app.
    var host by rememberSaveable(s.host) { mutableStateOf(s.host) }
    var port by rememberSaveable(s.port) { mutableStateOf(s.port.toString()) }
    var user by rememberSaveable(s.user) { mutableStateOf(s.user) }
    var regenStep by remember { mutableIntStateOf(0) }
    var tab by rememberSaveable { mutableIntStateOf(0) }
    val t = if (firstRun) 0 else tab
    val notifyPermission = rememberLauncherForActivityResult(ActivityResultContracts.RequestPermission()) { granted ->
        if (granted) vm.setNotify(true) else vm.say("Notifications stay off: Android didn't allow them. You can allow them in the phone's app settings.")
    }
    val chatLog by vm.chatLog.collectAsState()
    val keyRegenerated by vm.keyRegenerated.collectAsState()
    var confirmRemove by remember { mutableStateOf<Server?>(null) }
    val pushReady by vm.pushReady.collectAsState()
    var pushDialog by remember { mutableStateOf(false) }
    var pushKey by remember { mutableStateOf("") }
    val scope = rememberCoroutineScope()
    val appLock = LocalAppLock.current
    // Hidden by default; revealing asks for fingerprint/PIN when App lock is on.
    // Not saveable on purpose: leaving the screen hides it again.
    var showUser by remember { mutableStateOf(s.user.isBlank()) }

    if (pushDialog) {
        AlertDialog(
            onDismissRequest = { pushDialog = false; pushKey = "" },
            title = { Text("Instant alerts") },
            text = {
                Column(verticalArrangement = Arrangement.spacedBy(8.dp)) {
                    Text(
                        "Uses your own free Firebase project, so nothing is shared. In console.firebase.google.com create a project, then Project settings › Service accounts › Generate new private key, and paste the whole file here. The server does the rest.",
                        style = MaterialTheme.typography.bodySmall,
                    )
                    OutlinedTextField(value = pushKey, onValueChange = { pushKey = it }, label = { Text("Service-account JSON key") }, minLines = 3, maxLines = 6, modifier = Modifier.fillMaxWidth())
                }
            },
            confirmButton = { TextButton(enabled = pushKey.contains("private_key"), onClick = { vm.pushSetup(pushKey); pushDialog = false; pushKey = "" }) { Text("Save") } },
            dismissButton = { TextButton(onClick = { pushDialog = false; pushKey = "" }) { Text("Cancel") } },
        )
    }

    val portNum = port.toIntOrNull()?.takeIf { it in 1..65535 }
    val canSave = host.isNotBlank() && user.isNotBlank() && portNum != null && busy == null

    Column(
        Modifier.fillMaxSize().verticalScroll(rememberScrollState()).padding(16.dp),
        verticalArrangement = Arrangement.spacedBy(12.dp),
    ) {
        if (firstRun) {
            Text("Add your server", style = MaterialTheme.typography.headlineMedium)
            Step(1, "On your Linux server, open a terminal as the user Claude should run as.")
            Step(2, "Run this one command. It installs the cLaudeRC scripts and session auto-restore (asks for sudo once) and lets this phone in.")
            SelectionContainer {
                Text(
                    if (publicKey.isBlank()) "No key yet. Tap Regenerate." else "$ " + Updates.installCommand(publicKey),
                    fontFamily = FontFamily.Monospace,
                    fontSize = 12.sp,
                    color = Term.Fg,
                    modifier = Modifier.fillMaxWidth().background(Term.Field, RoundedCornerShape(14.dp))
                        .border(1.dp, Color(0xFF1F3A24), RoundedCornerShape(14.dp)).padding(14.dp),
                )
            }
            Row(horizontalArrangement = Arrangement.spacedBy(10.dp)) {
                Button(enabled = publicKey.isNotBlank(), onClick = {
                    copy(context, "Install command", Updates.installCommand(publicKey))
                }, modifier = Modifier.weight(1f)) { Text("Copy command") }
                OutlinedButton(enabled = publicKey.isNotBlank(), onClick = {
                    share(context, Updates.installCommand(publicKey))
                }, modifier = Modifier.weight(1f)) { Text("Share") }
                if (publicKey.isBlank()) TextButton(onClick = { vm.regenerateKey() }) { Text("Regenerate") }
            }
            Step(3, "When it finishes it prints the Host, Port and Username. Enter them below and tap Connect, then check the fingerprint matches one it printed and tap Trust.")
            Text("The server needs curl, jq, tmux, git and flock.", style = MaterialTheme.typography.bodySmall, color = MaterialTheme.colorScheme.onSurfaceVariant)
        }

        if (!firstRun) PillTabs(listOf("Connection", "Security", "App"), tab, { tab = it })

        // On first run the setup card above already carries the key.
        if (t == 1) {
            SectionLabel("This phone's key")
            Card(Modifier.fillMaxWidth()) {
                Column(Modifier.padding(12.dp), verticalArrangement = Arrangement.spacedBy(8.dp)) {
                    if (publicKey.isBlank()) {
                        Text("No key yet. Tap Regenerate to create one.", color = MaterialTheme.colorScheme.error, style = MaterialTheme.typography.bodySmall)
                    } else {
                        Text(
                            "The private key never leaves this phone. It is encrypted with the Android Keystore.",
                            style = MaterialTheme.typography.bodySmall,
                        )
                    }
                    // The install command is only needed after a new key: run it on each server.
                    if (keyRegenerated && publicKey.isNotBlank()) {
                        Text(
                            "New key created. Run this on each server (the app can't connect until you do):",
                            style = MaterialTheme.typography.bodyMedium,
                        )
                        SelectionContainer {
                            Text(Updates.installCommand(publicKey), fontFamily = FontFamily.Monospace, style = MaterialTheme.typography.bodySmall)
                        }
                        Button(onClick = { copy(context, "Install command", Updates.installCommand(publicKey)) }) {
                            Text("Copy install command")
                        }
                    }
                    TextButton(onClick = {
                        if (publicKey.isBlank()) vm.regenerateKey() else regenStep = 1
                    }) { Text("Regenerate", color = MaterialTheme.colorScheme.error) }
                }
            }

        }

        if (t == 0) {
        SectionLabel("Server")
        OutlinedTextField(
            value = host, onValueChange = { host = it.trim() },
            label = { Text("Host") }, placeholder = { Text("your-server.example.com") },
            singleLine = true, modifier = Modifier.fillMaxWidth(),
            keyboardOptions = KeyboardOptions(keyboardType = KeyboardType.Uri, autoCorrectEnabled = false),
        )
        Row(horizontalArrangement = Arrangement.spacedBy(8.dp)) {
            OutlinedTextField(
                value = port, onValueChange = { port = it.filter(Char::isDigit).take(5) },
                label = { Text("Port") }, singleLine = true, isError = portNum == null,
                modifier = Modifier.weight(0.35f),
                keyboardOptions = KeyboardOptions(keyboardType = KeyboardType.Number),
            )
            // Masked once entered; Show (behind App lock) reveals and allows editing.
            OutlinedTextField(
                value = user, onValueChange = { user = it.trim() },
                label = { Text("Username") }, singleLine = true,
                readOnly = !showUser,
                visualTransformation = if (showUser) VisualTransformation.None else PasswordVisualTransformation(),
                trailingIcon = {
                    IconButton(onClick = {
                        if (showUser) showUser = false
                        else scope.launch { if (appLock?.unlock("Show username") != false) showUser = true }
                    }) {
                        Icon(
                            if (showUser) Icons.Filled.VisibilityOff else Icons.Filled.Visibility,
                            contentDescription = if (showUser) "Hide username" else "Show username",
                        )
                    }
                },
                modifier = Modifier.weight(0.65f).onFocusChanged { f ->
                    if (!f.isFocused && user.isNotBlank()) showUser = false
                },
                keyboardOptions = KeyboardOptions(autoCorrectEnabled = false),
            )
        }
        Button(
            onClick = { vm.saveServerAndProbe(host, portNum ?: 22, user) },
            enabled = canSave,
            modifier = Modifier.fillMaxWidth(),
        ) { Text(if (s.hostKeyBlob.isEmpty()) "Connect" else "Save & re-check host key") }

        if (s.hostKeyFingerprint.isNotEmpty()) {
            Text("Pinned host key (${s.hostKeyType})", style = MaterialTheme.typography.labelLarge)
            SelectionContainer {
                Text(s.hostKeyFingerprint, fontFamily = FontFamily.Monospace, style = MaterialTheme.typography.bodySmall)
            }
            Row(horizontalArrangement = Arrangement.spacedBy(8.dp)) {
                OutlinedButton(onClick = { vm.testConnection() }, enabled = busy == null) { Text("Test connection") }
                TextButton(onClick = { vm.forgetHostKey() }) { Text("Forget host key") }
            }
        }

        }

        if (t == 0 && !firstRun) {
            val status by vm.status.collectAsState()
            if ((status?.scriptApi ?: 0) >= 43) {
                SectionLabel("Backup")
                DriveSection(vm)
            }
            SectionLabel("Servers")
            CardBox {
                Column(verticalArrangement = Arrangement.spacedBy(10.dp)) {
                    s.servers.filter { it.isConfigured }.forEach { srv ->
                        Row(verticalAlignment = Alignment.CenterVertically, horizontalArrangement = Arrangement.spacedBy(8.dp)) {
                            StatusDot(if (srv.id == s.activeId) Health.OK else Health.OFF)
                            Column(Modifier.weight(1f)) {
                                Text(srv.host, style = MaterialTheme.typography.bodyMedium, fontWeight = FontWeight.SemiBold)
                                Text(if (srv.id == s.activeId) "current" else "port ${srv.port}", style = MaterialTheme.typography.labelSmall, color = MaterialTheme.colorScheme.onSurfaceVariant)
                            }
                            if (srv.id != s.activeId) TextButton(onClick = { vm.switchServer(srv.id) }) { Text("Use") }
                            TextButton(onClick = { confirmRemove = srv }) { Text("Remove") }
                        }
                    }
                    OutlinedButton(onClick = { vm.addServer() }, modifier = Modifier.fillMaxWidth()) { Text("+ Add server") }
                }
            }

            SectionLabel("Migrate")
            CardBox {
                Row(verticalAlignment = Alignment.CenterVertically, horizontalArrangement = Arrangement.spacedBy(8.dp)) {
                    Column(Modifier.weight(1f)) {
                        Text("Migrate")
                        Text("Move everything from one server to another", style = MaterialTheme.typography.bodySmall, color = MaterialTheme.colorScheme.onSurfaceVariant)
                    }
                    OutlinedButton(onClick = { vm.migrateOpen() }) { Text("Open") }
                }
            }
        }

        if (t == 2) {
            SectionLabel("Notifications")
            CardBox {
                Column(verticalArrangement = Arrangement.spacedBy(10.dp)) {
                    Row(verticalAlignment = Alignment.CenterVertically) {
                        Column(Modifier.weight(1f)) {
                            Text("Session notifications")
                            Text(
                                "A session that needs an answer alerts you right away (needs push set up on the server; otherwise checked about every 15 minutes while the phone is unlocked). Turn on the bell on a session to hear when it finishes.",
                                style = MaterialTheme.typography.bodySmall, color = MaterialTheme.colorScheme.onSurfaceVariant,
                            )
                        }
                        Switch(checked = s.notify, onCheckedChange = { on ->
                            when {
                                !on -> vm.setNotify(false)
                                SessionWatcher.allowed(context) -> vm.setNotify(true)
                                // Android 13+: ask the user; turn on only if they allow it.
                                else -> notifyPermission.launch(android.Manifest.permission.POST_NOTIFICATIONS)
                            }
                        })
                    }
                    if (s.notify) OutlinedButton(onClick = { if (SessionWatcher.allowed(context)) SessionWatcher.test(context) else vm.say("Notifications are off for cLaudeRC in the phone's settings.") }) { Text("Send a test notification") }
                    if (s.notify && pushReady) OutlinedButton(onClick = { vm.pushTest() }) { Text("Send a test push (from the server)") }
                    if (s.notify) OutlinedButton(onClick = { pushDialog = true }) { Text(if (pushReady) "Change instant-alert key" else "Set up instant alerts") }
                }
            }
        }

        if (t == 1) {
            SectionLabel("Chat")
            CardBox {
                Row(verticalAlignment = Alignment.CenterVertically) {
                    Column(Modifier.weight(1f)) {
                        Text("Chat access log")
                        Text("Every chat open, message and upload, with time (never the contents).", style = MaterialTheme.typography.bodySmall, color = MaterialTheme.colorScheme.onSurfaceVariant)
                    }
                    OutlinedButton(onClick = { vm.loadChatLog() }) { Text("Show") }
                }
            }

            SectionLabel("Access")
            Row(verticalAlignment = Alignment.CenterVertically) {
                Column(Modifier.weight(1f)) {
                    Text("App lock")
                    Text(
                        "Required: to open the app, Settings and Run a command. Chat also needs its own PIN.",
                        style = MaterialTheme.typography.bodySmall,
                    )
                }
                Text("Always on", color = MaterialTheme.colorScheme.onSurfaceVariant, style = MaterialTheme.typography.bodyMedium)
            }
        }

        if (t == 2) {
            SectionLabel("Backup")
            AppBackupSection(vm)
            SectionLabel("Theme")
            SingleChoiceSegmentedButtonRow(Modifier.fillMaxWidth()) {
                ThemeMode.entries.forEachIndexed { i, m ->
                    SegmentedButton(
                        selected = s.theme == m,
                        onClick = { vm.setTheme(m) },
                        shape = SegmentedButtonDefaults.itemShape(i, ThemeMode.entries.size),
                    ) { Text(m.name.lowercase().replaceFirstChar { it.uppercase() }) }
                }
            }
        }
        Spacer(Modifier.padding(4.dp))
        Text(
            "cLaudeRC ${BuildConfig.VERSION_NAME} (${BuildConfig.VERSION_CODE})",
            style = MaterialTheme.typography.bodySmall,
        )
    }

    chatLog?.let { entries ->
        AlertDialog(
            onDismissRequest = { vm.clearChatLog() },
            title = { Text("Chat access log") },
            text = {
                Column(Modifier.heightIn(max = 420.dp).verticalScroll(rememberScrollState()), verticalArrangement = Arrangement.spacedBy(6.dp)) {
                    if (entries.isEmpty()) Text("No chat activity yet.")
                    entries.forEach { e ->
                        Row {
                            Text(e.ts.replace("T", " ").removeSuffix("Z").take(16), fontFamily = FontFamily.Monospace, style = MaterialTheme.typography.bodySmall, modifier = Modifier.weight(0.45f))
                            Text(e.session, style = MaterialTheme.typography.bodySmall, modifier = Modifier.weight(0.35f), maxLines = 1)
                            Text(e.action, style = MaterialTheme.typography.bodySmall, modifier = Modifier.weight(0.2f))
                        }
                    }
                    Text("Times are UTC. The log lives on the server in ~/.local/state/claude-launcher/chat.log.", style = MaterialTheme.typography.labelSmall, color = MaterialTheme.colorScheme.onSurfaceVariant)
                }
            },
            confirmButton = { TextButton(onClick = { vm.clearChatLog() }) { Text("Close") } },
        )
    }

    // Two warnings: a new key locks this phone out of every server until it's installed again.
    if (regenStep == 1) {
        AlertDialog(
            onDismissRequest = { regenStep = 0 },
            title = { Text("Regenerate this phone's key?") },
            text = { Text("The current key stops working on every server right away. You'll have to run the new install command on each server before the app can connect again.") },
            confirmButton = { TextButton(onClick = { regenStep = 2 }) { Text("Continue") } },
            dismissButton = { TextButton(onClick = { regenStep = 0 }) { Text("Cancel") } },
        )
    }
    if (regenStep == 2) {
        AlertDialog(
            onDismissRequest = { regenStep = 0 },
            title = { Text("Are you sure?") },
            text = { Text("This can't be undone. The old key is deleted from this phone.") },
            confirmButton = {
                TextButton(onClick = {
                    regenStep = 0
                    vm.regenerateKey()
                }) { Text("Yes, regenerate", color = MaterialTheme.colorScheme.error) }
            },
            dismissButton = { TextButton(onClick = { regenStep = 0 }) { Text("Cancel") } },
        )
    }

    confirmRemove?.let { srv ->
        AlertDialog(
            onDismissRequest = { confirmRemove = null },
            title = { Text("Remove ${srv.host}?") },
            text = {
                Text(
                    "The app forgets this server. This phone's key stays allowed on it until you run " +
                        "~/bin/install-launcher-key.sh --remove there.",
                )
            },
            confirmButton = {
                TextButton(onClick = { confirmRemove = null; vm.removeServer(srv.id) }) { Text("Remove") }
            },
            dismissButton = { TextButton(onClick = { confirmRemove = null }) { Text("Cancel") } },
        )
    }
}

/** A numbered step on the first-run screen. */
@Composable
private fun Step(n: Int, text: String) {
    Row(horizontalArrangement = Arrangement.spacedBy(12.dp)) {
        Box(Modifier.size(28.dp).background(MaterialTheme.colorScheme.primary, CircleShape), contentAlignment = Alignment.Center) {
            Text("$n", color = MaterialTheme.colorScheme.onPrimary, fontWeight = FontWeight.Bold)
        }
        Text(text, style = MaterialTheme.typography.bodyLarge)
    }
}

@Composable
fun HostKeyDialog(vm: MainViewModel, info: HostKeyInfo, previous: String) {
    val changed = previous.isNotEmpty() && previous != info.fingerprint
    AlertDialog(
        onDismissRequest = { vm.acceptHostKey(false) },
        title = { Text(if (changed) "Host key CHANGED" else "Trust this server?") },
        text = {
            Column(verticalArrangement = Arrangement.spacedBy(8.dp)) {
                if (changed) {
                    Text(
                        "The server now shows a different key than the one pinned. Only accept if you " +
                            "reinstalled the server or changed its SSH host keys.",
                        color = MaterialTheme.colorScheme.error,
                    )
                    Text("Pinned: $previous", fontFamily = FontFamily.Monospace, style = MaterialTheme.typography.bodySmall)
                }
                Text("Key type: ${info.type}")
                Text(info.fingerprint, fontFamily = FontFamily.Monospace, style = MaterialTheme.typography.bodySmall)
                Text(
                    "Compare with the output of this on the server:\n" +
                        "ssh-keygen -lf /etc/ssh/ssh_host_${info.type.removePrefix("ssh-").substringBefore('-')}_key.pub",
                    style = MaterialTheme.typography.bodySmall,
                )
            }
        },
        confirmButton = { TextButton(onClick = { vm.acceptHostKey(true) }) { Text("Trust") } },
        dismissButton = { TextButton(onClick = { vm.acceptHostKey(false) }) { Text("Cancel") } },
    )
}

internal fun copy(context: Context, label: String, text: String) {
    val cm = context.getSystemService(Context.CLIPBOARD_SERVICE) as ClipboardManager
    cm.setPrimaryClip(ClipData.newPlainText(label, text))
}

private fun share(context: Context, text: String) {
    val send = Intent(Intent.ACTION_SEND).setType("text/plain").putExtra(Intent.EXTRA_TEXT, text)
    context.startActivity(Intent.createChooser(send, "Share public key").addFlags(Intent.FLAG_ACTIVITY_NEW_TASK))
}
